-- Migration 011: GDPR Compliance — Cascading Deletes & Transaction Anonymization
--
-- Purpose:
--   Adjusts the transactions.user_id foreign key from ON DELETE CASCADE
--   to ON DELETE SET NULL. Financial records must be retained for legal
--   and accounting purposes even after a user deletes their account.
--
--   All other user-referencing foreign keys already use ON DELETE CASCADE
--   (verified in migrations 001, 003, 004, 005, 007, 008) which is the
--   correct behavior for GDPR's "Right to Erasure" — user-generated content
--   is removed when the user is deleted.
--
-- Changes:
--   1. Make transactions.user_id nullable (financial records survive user deletion)
--   2. Drop existing FK constraint on transactions.user_id
--   3. Re-create FK with ON DELETE SET NULL
--
-- Rationale:
--   GDPR Article 17 ("Right to Erasure") requires deletion of personal data,
--   but Recital 65 allows retention where "necessary for compliance with a
--   legal obligation" (e.g., tax/accounting records). Stripe requires
--   transaction records to be retained for dispute resolution.
--   Setting user_id to NULL anonymizes the record while preserving the
--   financial audit trail.
--
-- Existing ON DELETE CASCADE foreign keys (no changes needed):
--   - tenant_memberships.user_id → users(id) ON DELETE CASCADE  (migration 001)
--   - posts.author_id → users(id) ON DELETE CASCADE              (migration 003)
--   - invitations.invited_by → users(id) ON DELETE CASCADE       (migration 003)
--   - comments.author_id → users(id) ON DELETE CASCADE           (migration 004)
--   - notifications.recipient_id → users(id) ON DELETE CASCADE   (migration 005)
--   - follows.follower_id → users(id) ON DELETE CASCADE          (migration 007)
--   - follows.following_id → users(id) ON DELETE CASCADE         (migration 007)
--   - chat_channels.created_by → users(id) ON DELETE CASCADE     (migration 008)
--   - channel_members.user_id → users(id) ON DELETE CASCADE      (migration 008)
--   - chat_messages.user_id → users(id) ON DELETE CASCADE        (migration 008)

BEGIN;

-- Step 1: Make transactions.user_id nullable.
-- Financial records must survive user deletion (user_id becomes NULL).
ALTER TABLE public.transactions
  ALTER COLUMN user_id DROP NOT NULL;

-- Step 2: Drop the existing ON DELETE CASCADE constraint.
-- The constraint name is auto-generated by PG; find and drop it dynamically.
DO $$
DECLARE
  fk_name TEXT;
BEGIN
  SELECT tc.constraint_name INTO fk_name
  FROM information_schema.table_constraints tc
  JOIN information_schema.key_column_usage kcu
    ON tc.constraint_name = kcu.constraint_name
    AND tc.table_schema = kcu.table_schema
  WHERE tc.constraint_type = 'FOREIGN KEY'
    AND tc.table_schema = 'public'
    AND tc.table_name = 'transactions'
    AND kcu.column_name = 'user_id';

  IF fk_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.transactions DROP CONSTRAINT %I', fk_name);
  END IF;
END $$;

-- Step 3: Re-create with ON DELETE SET NULL.
-- When a user is deleted, their transaction records are preserved
-- with user_id = NULL (anonymized).
ALTER TABLE public.transactions
  ADD CONSTRAINT transactions_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES public.users(id)
  ON DELETE SET NULL;

-- Step 4: Update the RLS INSERT policy to allow NULL user_id check
-- (the existing INSERT policy checks user_id = auth.uid(), which still works
-- because we only set NULL via cascade, never via direct insert).
-- No RLS policy changes needed — the INSERT policy remains:
--   user_id = (auth.uid())::uuid AND tenant_id = current_tenant_id
-- The SET NULL only fires on user deletion (service role), not on INSERT.

COMMIT;
