-- =============================================================================
-- Migration 012: Church Registration, Tiers, and Granular Admin Permissions
--
-- Adds:
--   1. tier + registration_key columns to tenants (for self-service registration)
--   2. permissions JSONB column to tenant_memberships (granular sub-admin perms)
--   3. roles reference table with default role definitions and permissions
--   4. slug column on tenants (the "Church App ID" from registration)
--   5. RLS policies for the new roles table
--
-- Depends on: 001_initial_schema_and_rls.sql (tenants, tenant_memberships)
-- =============================================================================

-- ============================================================================
-- SECTION 1: Alter tenants table
-- ============================================================================

-- Tier determines the feature set available to the church
ALTER TABLE public.tenants
  ADD COLUMN IF NOT EXISTS tier TEXT NOT NULL DEFAULT 'standard'
    CHECK (tier IN ('standard', 'premium', 'enterprise'));

-- Registration key — unique invite code for self-service church registration.
-- Pre-generated by platform admins; consumed during POST /tenants/register.
ALTER TABLE public.tenants
  ADD COLUMN IF NOT EXISTS registration_key TEXT UNIQUE;

-- Slug — the human-readable "Church App ID" (e.g., "grace-church").
-- Used in URLs and deep links. Must be unique and lowercase alphanumeric + dashes.
ALTER TABLE public.tenants
  ADD COLUMN IF NOT EXISTS slug TEXT UNIQUE
    CHECK (slug ~ '^[a-z0-9][a-z0-9-]*[a-z0-9]$' OR slug ~ '^[a-z0-9]$');

COMMENT ON COLUMN public.tenants.tier IS
  'Subscription tier: standard (free), premium, enterprise. Controls feature gates.';
COMMENT ON COLUMN public.tenants.registration_key IS
  'One-time invite code consumed during church self-registration. NULL after use or if created by super admin.';
COMMENT ON COLUMN public.tenants.slug IS
  'URL-friendly church identifier (e.g., grace-church). Set during registration.';


-- ============================================================================
-- SECTION 2: Alter tenant_memberships table
-- ============================================================================

-- Granular permissions JSONB — allows sub-admin roles (accountant, worship leader)
-- to have specific capabilities beyond the base role.
ALTER TABLE public.tenant_memberships
  ADD COLUMN IF NOT EXISTS permissions JSONB NOT NULL DEFAULT '{}';

COMMENT ON COLUMN public.tenant_memberships.permissions IS
  'Granular permission overrides as JSONB. Keys: manage_finance, manage_content, manage_members, manage_worship, view_analytics. Values: true/false.';


-- ============================================================================
-- SECTION 3: Create roles reference table
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.roles (
  id    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name  TEXT UNIQUE NOT NULL,
  permissions JSONB NOT NULL DEFAULT '{}'
);

COMMENT ON TABLE public.roles IS
  'Reference table defining standard roles and their default permission sets. '
  'Used as a template when assigning roles — actual permissions are stored on tenant_memberships.';

-- Seed default roles with their permission templates
INSERT INTO public.roles (name, permissions) VALUES
  ('admin', '{
    "manage_finance": true,
    "manage_content": true,
    "manage_members": true,
    "manage_worship": true,
    "view_analytics": true
  }'::jsonb),
  ('pastor', '{
    "manage_finance": false,
    "manage_content": true,
    "manage_members": true,
    "manage_worship": true,
    "view_analytics": true
  }'::jsonb),
  ('accountant', '{
    "manage_finance": true,
    "manage_content": false,
    "manage_members": false,
    "manage_worship": false,
    "view_analytics": true
  }'::jsonb),
  ('worship_leader', '{
    "manage_finance": false,
    "manage_content": true,
    "manage_members": false,
    "manage_worship": true,
    "view_analytics": false
  }'::jsonb),
  ('member', '{
    "manage_finance": false,
    "manage_content": false,
    "manage_members": false,
    "manage_worship": false,
    "view_analytics": false
  }'::jsonb)
ON CONFLICT (name) DO NOTHING;


-- ============================================================================
-- SECTION 4: RLS on roles table
-- ============================================================================

ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles FORCE ROW LEVEL SECURITY;

-- Roles are a public reference table — any authenticated user can read them
CREATE POLICY "roles: select for authenticated users"
  ON public.roles
  FOR SELECT
  TO authenticated
  USING (true);

-- Only service role can modify roles (no INSERT/UPDATE/DELETE for authenticated)
-- This is enforced by the absence of INSERT/UPDATE/DELETE policies.


-- ============================================================================
-- SECTION 5: Create registration_keys table for pre-generated invite codes
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.registration_keys (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  key         TEXT UNIQUE NOT NULL,
  tier        TEXT NOT NULL DEFAULT 'standard'
              CHECK (tier IN ('standard', 'premium', 'enterprise')),
  claimed_by  UUID REFERENCES public.tenants(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  claimed_at  TIMESTAMPTZ
);

COMMENT ON TABLE public.registration_keys IS
  'Pre-generated registration keys that churches use for self-service signup. '
  'Each key maps to a tier and can only be claimed once.';

ALTER TABLE public.registration_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registration_keys FORCE ROW LEVEL SECURITY;

-- No authenticated user policies — registration keys are only accessed
-- by the service role during the registration flow.


-- ============================================================================
-- SECTION 6: Expand role CHECK constraint on tenant_memberships
-- ============================================================================

-- The existing CHECK constraint only allows 'admin', 'pastor', 'member'.
-- We need to add 'accountant' and 'worship_leader'.
ALTER TABLE public.tenant_memberships
  DROP CONSTRAINT IF EXISTS tenant_memberships_role_check;

ALTER TABLE public.tenant_memberships
  ADD CONSTRAINT tenant_memberships_role_check
  CHECK (role IN ('admin', 'pastor', 'accountant', 'worship_leader', 'member'));


-- ============================================================================
-- SECTION 7: Seed a few registration keys for testing
-- ============================================================================

INSERT INTO public.registration_keys (key, tier) VALUES
  ('NG-TEST-STD1', 'standard'),
  ('NG-TEST-PRE1', 'premium'),
  ('NG-TEST-ENT1', 'enterprise')
ON CONFLICT (key) DO NOTHING;


-- ============================================================================
-- Verification queries (uncomment to run manually)
-- ============================================================================
-- SELECT column_name, data_type, is_nullable, column_default
-- FROM information_schema.columns
-- WHERE table_schema = 'public' AND table_name = 'tenants'
-- ORDER BY ordinal_position;

-- SELECT column_name, data_type, is_nullable, column_default
-- FROM information_schema.columns
-- WHERE table_schema = 'public' AND table_name = 'tenant_memberships'
-- ORDER BY ordinal_position;

-- SELECT * FROM public.roles;
-- SELECT * FROM public.registration_keys;
